site_name: Reggi
theme:
  name: material
  logo: ../assets/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
  - glightbox


nav:
    - Home: index.md
    - Install:
      - install/index.md
      - 'iOS': 'install/ios.md'
      - 'Android': 'install/android.md'
    - Troubleshooting:
      - troubleshooting/index.md
      - 'iOS: White Screen': 'troubleshooting/ios-white-screen.md'
    - Contribute:
      - contribute/index.md
      - 'Local Docs Development Environment Setup': 'contribute/local-development/'