name: Send discord message

on: [push, pull_request]

jobs:
  send-discord:
    name: Send discord message
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Waiting 10 seconds"

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Discord notification
        if: jobs.<job_id>.if == 'success'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'SUCCESS: Branch: ${{ github.ref_name }}' 
      
      - name: A/B Check
        if: ${{ envA }} != ${{ envB }}
        run: |
          echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
          exit 1
      
      
      - name: Discord notification fail
        if: jobs.<job_id>.if == 'failure'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'FAILURE: Branch: ${{ github.ref_name }}'