name: Build and Deploy mkdocs to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build-and-deploy:
    name: Build and Deploy mkdocs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: 'latest' # option
          #mkdocs_version: '1.1' # option
          requirements: 'requirements.txt' # option
          configfile: 'mkdocs.yml' # option

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

      - name: Post to a Slack channel
        if: always()
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel ID where message will be posted. Needed if using bot token
          channel-id: 'C04JZM55VC2'
          # Message to post into Slack. Needed if using bot token
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Actions for Discord
        uses: Ilshidur/action-discord@0.3.2


      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD }} has been deployed.'